### ISSUE TITLE
venue crash

### ISSUE THREAD

**Issue by darylferris** [brownieboy/manlyhappyhour#1]
when I click on the first 2 venues (The Office and 4 Pines) the app crashed.
other venues work fine.

**Comment by brownieboy** [comment]
@darylferris 

Hmm...not seen that.

Can you check which version you have installed?  To do that, got to the information tab (bottom right), then About the App, then scroll down to the bottom.  You should see a version number and build number there.

**Comment by darylferris** [comment]
video of crash

**Comment by brownieboy** [comment]
@darylferris 

That's an old version.  You can delete that and download it from the App Store (_not_ from Test Flight).

Just open the App Store app on your phone and search for "Manly Happy Hour".

**Comment by darylferris** [comment]
ah..updated..works fine now..sweet!
